package main

import (
	"context"
	"errors"
	"fmt"
	"io/fs"
	"log/slog"
	"math"
	"os"
	"runtime/debug"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/joho/godotenv"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/ttab/elephant-api/repository"
	"github.com/ttab/elephant-replicant/internal"
	"github.com/ttab/elephantine"
	"github.com/ttab/elephantine/pg"
	"github.com/urfave/cli/v3"
	"golang.org/x/oauth2"
)

var version string // set via -ldflags at build time

// DefaultDBMaxConns is the size of the query pool, set here rather than left
// to pgx: its default is max(4, NumCPU()) read from the node's cpuset rather
// than the cgroup quota, so an unset pool tracks whichever node the pod lands
// on and changes size invisibly on reschedule.
//
// The replicant's concurrency is its targets, not request traffic. Each enabled
// target runs one worker that handles events one at a time and holds at most
// one transaction, which stays open across the calls to the target repository,
// and one job lock whose ping runs every ten seconds with a five second timeout.
// A ping that cannot get a connection in time loses the lock and restarts the
// worker, so each target needs two connections: three targets is six. The
// admin RPCs, the hourly mapping cleanup and, without a bouncer, the LISTEN
// connection that the subscriber hijacks out of the pool take the last two.
// Raise it with DB_MAX_CONNS when running more than three targets.
const DefaultDBMaxConns = 8

// listenPoolMaxConns is the size of the direct pool when queries go through a
// bouncer: it then carries only the LISTEN session, which the subscriber
// hijacks out of the pool, plus one spare.
const listenPoolMaxConns = 2

func main() {
	err := godotenv.Load()
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		slog.Error("exiting: ",
			elephantine.LogKeyError, err)
		os.Exit(1)
	}

	runCmd := cli.Command{
		Name:        "run",
		Description: "Runs the service",
		Action:      runReplicant,
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:    "addr",
				Sources: cli.EnvVars("ADDR"),
				Value:   ":1080",
			},
			&cli.StringFlag{
				Name:    "profile-addr",
				Sources: cli.EnvVars("PROFILE_ADDR"),
				Value:   ":1081",
			},
			&cli.StringFlag{
				Name:    "tls-addr",
				Value:   ":1443",
				Sources: cli.EnvVars("TLS_ADDR", "TLS_LISTEN_ADDR"),
			},
			&cli.StringFlag{
				Name:    "cert-file",
				Sources: cli.EnvVars("TLS_CERT_PATH"),
			},
			&cli.StringFlag{
				Name:    "key-file",
				Sources: cli.EnvVars("TLS_KEY_PATH"),
			},
			&cli.StringFlag{
				Name:    "log-level",
				Sources: cli.EnvVars("LOG_LEVEL"),
				Value:   "info",
			},
			&cli.StringFlag{
				Name:     "repository-endpoint",
				Sources:  cli.EnvVars("REPOSITORY_ENDPOINT"),
				Required: true,
				Value:    "http://editorial-repository:1080",
			},
			&cli.StringFlag{ //nolint: gosec
				Name:    "db",
				Value:   "postgres://elephant-replicant:pass@localhost/elephant-replicant",
				Sources: cli.EnvVars("CONN_STRING"),
			},
			&cli.StringFlag{
				Name:    "db-bouncer",
				Sources: cli.EnvVars("BOUNCER_CONN_STRING"),
				Usage: `Connection string for a transaction pooler such as
PgBouncer. When set, all queries go through it and the direct connection only
carries the LISTEN session.`,
			},
			&cli.IntFlag{
				Name:    "db-max-conns",
				Sources: cli.EnvVars("DB_MAX_CONNS"),
				Value:   DefaultDBMaxConns,
				Usage: `Maximum size of the Postgres connection pool used for
queries. Overrides pool_max_conns in the connection string. Zero or less leaves
the pool to size itself, which means max(4, NumCPU()) read from the node's
cpuset. With a bouncer configured the direct pool is fixed at 2 and this applies
to the bouncer pool.`,
			},
			&cli.StringSliceFlag{
				Name:    "cors-hosts",
				Sources: cli.EnvVars("CORS_HOSTS"),
			},
			&cli.StringSliceFlag{
				Name:    "ignore-types",
				Sources: cli.EnvVars("IGNORE_TYPES"),
				Usage:   "Document types to ignore when replicating",
			},
			&cli.StringSliceFlag{
				Name:    "ignore-subs",
				Sources: cli.EnvVars("IGNORE_SUBS"),
				Usage:   "Ignore events generated by these client subs.",
			},
			&cli.StringSliceFlag{
				Name:    "ignore-section",
				Sources: cli.EnvVars("IGNORE_SECTIONS"),
				Usage:   "The UUID of sections to ignore prefixed with document type. Example: 'core/event:0730efa9-43f2-468d-979a-aaffc74d7582'", //nolint: lll
			},
			&cli.StringSliceFlag{
				Name:    "include-attachments",
				Sources: cli.EnvVars("INCLUDE_ATTACHMENTS"),
				Usage:   "Attachment references in the format '[name].[document type]', example 'image.core/image'",
			},
			&cli.BoolFlag{
				Name:    "all-attachments",
				Sources: cli.EnvVars("ALL_ATTACHMENTS"),
				Usage:   "Replicate all attachments",
			},
			&cli.Int64Flag{
				Name:    "start-event",
				Sources: cli.EnvVars("START_EVENT"),
				Usage:   "The event to start replication at",
			},
			&cli.StringFlag{
				Name:    "target-oidc-config",
				Sources: cli.EnvVars("TARGET_OIDC_CONFIG"),
			},
			&cli.StringFlag{
				Name:    "target-client-id",
				Sources: cli.EnvVars("TARGET_CLIENT_ID"),
			},
			&cli.StringFlag{
				Name:    "target-client-secret",
				Sources: cli.EnvVars("TARGET_CLIENT_SECRET"),
			},
			&cli.StringFlag{
				Name:    "target-repository-endpoint",
				Sources: cli.EnvVars("TARGET_REPOSITORY_ENDPOINT"),
			},
			&cli.BoolFlag{
				Name:    "accept-errors",
				Sources: cli.EnvVars("ACCEPT_ERRORS"),
			},
			&cli.StringFlag{
				Name:     "encryption-key",
				Sources:  cli.EnvVars("ENCRYPTION_KEY"),
				Required: true,
				Usage:    "64-character hex-encoded AES-256 key for encrypting client secrets at rest",
			},
		},
	}

	runCmd.Flags = append(runCmd.Flags, elephantine.AuthenticationCLIFlags()...)

	app := cli.Command{
		Name:  "elephant-replicant",
		Usage: "The Elephant replicant",
		Commands: []*cli.Command{
			&runCmd,
		},
	}

	if err := app.Run(context.Background(), os.Args); err != nil {
		slog.Error("failed to run application",
			elephantine.LogKeyError, err)
		os.Exit(1)
	}
}

var sourceScopes = []string{"doc_read_all", "eventlog_read"}

func runReplicant(ctx context.Context, c *cli.Command) error {
	var (
		addr               = c.String("addr")
		profileAddr        = c.String("profile-addr")
		tlsAddr            = c.String("tls-addr")
		certFile           = c.String("cert-file")
		keyFile            = c.String("key-file")
		logLevel           = c.String("log-level")
		repositoryEndpoint = c.String("repository-endpoint")
		targetEndpoint     = c.String("target-repository-endpoint")
		corsHosts          = c.StringSlice("cors-hosts")
		ignoreTypes        = c.StringSlice("ignore-types")
		ignoreSubs         = c.StringSlice("ignore-subs")
		ignoreSections     = c.StringSlice("ignore-section")
		includeAttachments = c.StringSlice("include-attachments")
		allAttachments     = c.Bool("all-attachments")
		startEvent         = c.Int64("start-event")
		acceptErrors       = c.Bool("accept-errors")
	)

	logger := elephantine.SetUpLogger(logLevel, os.Stdout)

	encryptionKey, err := internal.ParseEncryptionKey(c.String("encryption-key"))
	if err != nil {
		return fmt.Errorf("parse encryption key: %w", err)
	}

	logger.Info("parsed encryption key")

	var incAttachments []internal.AttachmentRef

	for _, s := range includeAttachments {
		ref, err := internal.AttachmentRefFromString(s)
		if err != nil {
			return fmt.Errorf("invalid 'include-attachments': %w", err)
		}

		incAttachments = append(incAttachments, ref)
	}

	defer func() {
		if p := recover(); p != nil {
			slog.ErrorContext(ctx, "panic during setup",
				elephantine.LogKeyError, p,
				"stack", string(debug.Stack()),
			)

			os.Exit(2)
		}
	}()

	logger.Info("connecting to database")

	var (
		connString        = c.String("db")
		bouncerConnString = c.String("db-bouncer")
		dbMaxConns        = c.Int("db-max-conns")
		useBouncer        = bouncerConnString != "" && bouncerConnString != connString
	)

	pubsubMaxConns := dbMaxConns
	if useBouncer {
		pubsubMaxConns = listenPoolMaxConns
	}

	pubsubPool, err := newPool(ctx, connString, pubsubMaxConns)
	if err != nil {
		return fmt.Errorf("direct database: %w", err)
	}

	defer func() {
		// Don't block for close.
		go pubsubPool.Close()
	}()

	dbpool := pubsubPool

	if useBouncer {
		dbpool, err = newPool(ctx, bouncerConnString, dbMaxConns)
		if err != nil {
			return fmt.Errorf("bouncer database: %w", err)
		}

		defer func() {
			go dbpool.Close()
		}()
	}

	logger.Info("created connection pools",
		"max_conns", dbMaxConns,
		"direct_max_conns", pubsubMaxConns,
		"bouncer", useBouncer)

	// The pubsub pool doubles as the main pool when no bouncer is
	// configured, and is then only registered once.
	poolCollectors := map[string]*pgxpool.Pool{"main": dbpool}
	if dbpool != pubsubPool {
		poolCollectors["pubsub"] = pubsubPool
	}

	for name, pool := range poolCollectors {
		err = prometheus.DefaultRegisterer.Register(
			pg.NewPoolStatCollector(pool, name))
		if err != nil {
			return fmt.Errorf("register %s pool metrics: %w", name, err)
		}
	}

	logger.Info("setting up source authentication")

	auth, err := elephantine.AuthenticationConfigFromCLI(ctx, c, sourceScopes)
	if err != nil {
		return fmt.Errorf("set up authentication: %w", err)
	}

	logger.Info("verifying source credentials")

	_, err = auth.TokenSource.Token()
	if err != nil {
		return fmt.Errorf("verify credentials: %w", err)
	}

	elephantClient := oauth2.NewClient(ctx, auth.TokenSource)

	documents := repository.NewDocumentsProtobufClient(
		repositoryEndpoint, elephantClient,
	)

	serverOpts := []elephantine.APIServerOption{
		elephantine.APIServerCORSHosts(corsHosts...),
		elephantine.APIServerVersion(version),
	}

	if certFile != "" {
		serverOpts = append(serverOpts,
			elephantine.APIServerTLS(tlsAddr, certFile, keyFile))
	}

	server := elephantine.NewAPIServer(logger, addr, profileAddr, serverOpts...)

	var defaultTarget *internal.DefaultTargetConfig

	if targetEndpoint != "" {
		if repositoryEndpoint == targetEndpoint {
			return errors.New("source and target cannot be the same")
		}

		defaultTarget = &internal.DefaultTargetConfig{
			RepositoryURL:      targetEndpoint,
			OIDCConfig:         c.String("target-oidc-config"),
			ClientID:           c.String("target-client-id"),
			ClientSecret:       c.String("target-client-secret"),
			StartFrom:          startEvent,
			IgnoreTypes:        ignoreTypes,
			IgnoreSubs:         ignoreSubs,
			IgnoreSections:     ignoreSections,
			IncludeAttachments: incAttachments,
			AllAttachments:     allAttachments,
			AcceptErrors:       acceptErrors,
		}
	}

	logger.Info("starting service")

	err = internal.Run(ctx, internal.Parameters{
		Server:            server,
		Logger:            logger,
		Database:          dbpool,
		ListenDatabase:    pubsubPool,
		Documents:         documents,
		CORSHosts:         corsHosts,
		MetricsRegisterer: prometheus.DefaultRegisterer,
		AuthInfoParser:    auth.AuthParser,
		DefaultTarget:     defaultTarget,
		EncryptionKey:     encryptionKey,
	})
	if err != nil {
		return fmt.Errorf("run application: %w", err)
	}

	return nil
}

// newPool creates a connection pool and verifies that the database answers.
// A positive maxConns sizes the pool; zero or less leaves that to the
// connection string or pgx.
func newPool(
	ctx context.Context, connString string, maxConns int,
) (*pgxpool.Pool, error) {
	conf, err := pgxpool.ParseConfig(connString)
	if err != nil {
		return nil, fmt.Errorf("parse connection string: %w", err)
	}

	if maxConns > math.MaxInt32 {
		return nil, fmt.Errorf("max conns %d exceeds %d", maxConns, math.MaxInt32)
	}

	if maxConns > 0 {
		conf.MaxConns = int32(maxConns)
	}

	pool, err := pgxpool.NewWithConfig(ctx, conf)
	if err != nil {
		return nil, fmt.Errorf("create connection pool: %w", err)
	}

	err = pool.Ping(ctx)
	if err != nil {
		pool.Close()

		return nil, fmt.Errorf("connect to database: %w", err)
	}

	return pool, nil
}
