package main

import (
	"context"
	"errors"
	"fmt"
	"io/fs"
	"log/slog"
	"os"
	"runtime/debug"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/joho/godotenv"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/ttab/elephant-api/repository"
	"github.com/ttab/elephant-replicant/internal"
	"github.com/ttab/elephantine"
	"github.com/urfave/cli/v3"
	"golang.org/x/oauth2"
)

func main() {
	err := godotenv.Load()
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		slog.Error("exiting: ",
			elephantine.LogKeyError, err)
		os.Exit(1)
	}

	runCmd := cli.Command{
		Name:        "run",
		Description: "Runs the service",
		Action:      runReplicant,
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:    "addr",
				Sources: cli.EnvVars("ADDR"),
				Value:   ":1080",
			},
			&cli.StringFlag{
				Name:    "profile-addr",
				Sources: cli.EnvVars("PROFILE_ADDR"),
				Value:   ":1081",
			},
			&cli.StringFlag{
				Name:    "log-level",
				Sources: cli.EnvVars("LOG_LEVEL"),
				Value:   "info",
			},
			&cli.StringFlag{
				Name:     "repository-endpoint",
				Sources:  cli.EnvVars("REPOSITORY_ENDPOINT"),
				Required: true,
				Value:    "http://editorial-repository:1080",
			},
			&cli.StringFlag{ //nolint: gosec
				Name:    "db",
				Value:   "postgres://elephant-replicant:pass@localhost/elephant-replicant",
				Sources: cli.EnvVars("CONN_STRING"),
			},
			&cli.StringSliceFlag{
				Name:    "cors-hosts",
				Sources: cli.EnvVars("CORS_HOSTS"),
			},
			&cli.StringSliceFlag{
				Name:    "ignore-types",
				Sources: cli.EnvVars("IGNORE_TYPES"),
				Usage:   "Document types to ignore when replicating",
			},
			&cli.StringSliceFlag{
				Name:    "ignore-subs",
				Sources: cli.EnvVars("IGNORE_SUBS"),
				Usage:   "Ignore events generated by these client subs.",
			},
			&cli.StringSliceFlag{
				Name:    "ignore-section",
				Sources: cli.EnvVars("IGNORE_SECTIONS"),
				Usage:   "The UUID of sections to ignore prefixed with document type. Example: 'core/event:0730efa9-43f2-468d-979a-aaffc74d7582'", //nolint: lll
			},
			&cli.StringSliceFlag{
				Name:    "include-attachments",
				Sources: cli.EnvVars("INCLUDE_ATTACHMENTS"),
				Usage:   "Attachment references in the format '[name].[document type]', example 'image.core/image'",
			},
			&cli.BoolFlag{
				Name:    "all-attachments",
				Sources: cli.EnvVars("ALL_ATTACHMENTS"),
				Usage:   "Replicate all attachments",
			},
			&cli.Int64Flag{
				Name:    "start-event",
				Sources: cli.EnvVars("START_EVENT"),
				Usage:   "The event to start replication at",
			},
			&cli.StringFlag{
				Name:    "target-oidc-config",
				Sources: cli.EnvVars("TARGET_OIDC_CONFIG"),
			},
			&cli.StringFlag{
				Name:    "target-client-id",
				Sources: cli.EnvVars("TARGET_CLIENT_ID"),
			},
			&cli.StringFlag{
				Name:    "target-client-secret",
				Sources: cli.EnvVars("TARGET_CLIENT_SECRET"),
			},
			&cli.StringFlag{
				Name:    "target-repository-endpoint",
				Sources: cli.EnvVars("TARGET_REPOSITORY_ENDPOINT"),
			},
			&cli.BoolFlag{
				Name:    "accept-errors",
				Sources: cli.EnvVars("ACCEPT_ERRORS"),
			},
			&cli.StringFlag{
				Name:     "encryption-key",
				Sources:  cli.EnvVars("ENCRYPTION_KEY"),
				Required: true,
				Usage:    "64-character hex-encoded AES-256 key for encrypting client secrets at rest",
			},
		},
	}

	runCmd.Flags = append(runCmd.Flags, elephantine.AuthenticationCLIFlags()...)

	app := cli.Command{
		Name:  "elephant-replicant",
		Usage: "The Elephant replicant",
		Commands: []*cli.Command{
			&runCmd,
		},
	}

	if err := app.Run(context.Background(), os.Args); err != nil {
		slog.Error("failed to run application",
			elephantine.LogKeyError, err)
		os.Exit(1)
	}
}

var sourceScopes = []string{"doc_read_all", "eventlog_read"}

func runReplicant(ctx context.Context, c *cli.Command) error {
	var (
		addr               = c.String("addr")
		profileAddr        = c.String("profile-addr")
		logLevel           = c.String("log-level")
		repositoryEndpoint = c.String("repository-endpoint")
		targetEndpoint     = c.String("target-repository-endpoint")
		corsHosts          = c.StringSlice("cors-hosts")
		ignoreTypes        = c.StringSlice("ignore-types")
		ignoreSubs         = c.StringSlice("ignore-subs")
		ignoreSections     = c.StringSlice("ignore-section")
		includeAttachments = c.StringSlice("include-attachments")
		allAttachments     = c.Bool("all-attachments")
		startEvent         = c.Int64("start-event")
		acceptErrors       = c.Bool("accept-errors")
	)

	logger := elephantine.SetUpLogger(logLevel, os.Stdout)

	encryptionKey, err := internal.ParseEncryptionKey(c.String("encryption-key"))
	if err != nil {
		return fmt.Errorf("parse encryption key: %w", err)
	}

	logger.Info("parsed encryption key")

	var incAttachments []internal.AttachmentRef

	for _, s := range includeAttachments {
		ref, err := internal.AttachmentRefFromString(s)
		if err != nil {
			return fmt.Errorf("invalid 'include-attachments': %w", err)
		}

		incAttachments = append(incAttachments, ref)
	}

	defer func() {
		if p := recover(); p != nil {
			slog.ErrorContext(ctx, "panic during setup",
				elephantine.LogKeyError, p,
				"stack", string(debug.Stack()),
			)

			os.Exit(2)
		}
	}()

	logger.Info("connecting to database")

	dbpool, err := pgxpool.New(ctx, c.String("db"))
	if err != nil {
		return fmt.Errorf("create connection pool: %w", err)
	}

	defer func() {
		// Don't block for close.
		go dbpool.Close()
	}()

	err = dbpool.Ping(ctx)
	if err != nil {
		return fmt.Errorf("connect to database: %w", err)
	}

	logger.Info("setting up source authentication")

	auth, err := elephantine.AuthenticationConfigFromCLI(ctx, c, sourceScopes)
	if err != nil {
		return fmt.Errorf("set up authentication: %w", err)
	}

	logger.Info("verifying source credentials")

	_, err = auth.TokenSource.Token()
	if err != nil {
		return fmt.Errorf("verify credentials: %w", err)
	}

	elephantClient := oauth2.NewClient(ctx, auth.TokenSource)

	documents := repository.NewDocumentsProtobufClient(
		repositoryEndpoint, elephantClient,
	)

	server := elephantine.NewAPIServer(logger, addr, profileAddr,
		elephantine.APIServerCORSHosts(corsHosts...))

	var defaultTarget *internal.DefaultTargetConfig

	if targetEndpoint != "" {
		if repositoryEndpoint == targetEndpoint {
			return errors.New("source and target cannot be the same")
		}

		defaultTarget = &internal.DefaultTargetConfig{
			RepositoryURL:      targetEndpoint,
			OIDCConfig:         c.String("target-oidc-config"),
			ClientID:           c.String("target-client-id"),
			ClientSecret:       c.String("target-client-secret"),
			StartFrom:          startEvent,
			IgnoreTypes:        ignoreTypes,
			IgnoreSubs:         ignoreSubs,
			IgnoreSections:     ignoreSections,
			IncludeAttachments: incAttachments,
			AllAttachments:     allAttachments,
			AcceptErrors:       acceptErrors,
		}
	}

	logger.Info("starting service")

	err = internal.Run(ctx, internal.Parameters{
		Server:            server,
		Logger:            logger,
		Database:          dbpool,
		Documents:         documents,
		CORSHosts:         corsHosts,
		MetricsRegisterer: prometheus.DefaultRegisterer,
		AuthInfoParser:    auth.AuthParser,
		DefaultTarget:     defaultTarget,
		EncryptionKey:     encryptionKey,
	})
	if err != nil {
		return fmt.Errorf("run application: %w", err)
	}

	return nil
}
