// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Document struct {
	ID            uuid.UUID
	TargetVersion int64
}

type SchemaVersion struct {
	Version int32
}

type State struct {
	Name  string
	Value []byte
}

type VersionMapping struct {
	ID            uuid.UUID
	SourceVersion int64
	TargetVersion int64
	Created       pgtype.Timestamptz
}
