// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Document struct {
	ID            uuid.UUID
	TargetVersion int64
	TargetName    string
}

type JobLock struct {
	Name      string
	Holder    string
	Touched   pgtype.Timestamptz
	Iteration int64
}

type ReplicationTarget struct {
	Name          string
	RepositoryUrl string
	OidcConfig    string
	ClientID      string
	ClientSecret  string
	StartFrom     int64
	Config        []byte
	Enabled       bool
	Created       pgtype.Timestamptz
	Updated       pgtype.Timestamptz
}

type SchemaVersion struct {
	Version int32
}

type State struct {
	Name  string
	Value []byte
}

type VersionMapping struct {
	ID            uuid.UUID
	SourceVersion int64
	TargetVersion int64
	Created       pgtype.Timestamptz
	TargetName    string
}
